### PR TITLE
continuous deployment with netlify

### LINKED ISSUE #633: [Doc]: add build script
本家のドキュメントに更新がありました:page_facing_up:
Original:https://github.com/vuejs/vuejs.org/commit/42c9a22d7f4b813e8580249bdb98e1451d74c58a

### LINKED ISSUE #634: Continuous deployment using netlify
First all, 頑張ってくれてありがとう! 🙇

I have moved the deployment of vuejs.org to [Netlify](https://www.netlify.com/), which has automated continuous deployment whenever the github repo is updated. It removes the need of manual deployments, and from my testing also has better performance than GitHub pages (their CDN routes traffic from Asia to AWS Japan!)

If you guys are ok with this I can set it up easily, the only thing needed is having [this update](https://github.com/vuejs/vuejs.org/commit/42c9a22d7f4b813e8580249bdb98e1451d74c58a) cherry picked here.

### LINKED ISSUE #635: [Doc]: update deploy docs
本家のドキュメントに更新がありました:page_facing_up:
Original:https://github.com/vuejs/vuejs.org/commit/36f1a019c7f46e4d7525b7241ef34cd39d1178c5

### PR DESCRIPTION
**Pull request by kazupon**
closes #633 closes #634 closes #635

### CODE REVIEW

**Comment by re-fort** [comment]
@kazupon
NetlifyのセットアップをしてもらってからこのPRをマージであってます？

**Comment by yyx990803** [comment]
@re-fort I will setup Netlify with a `vuejs-jp` team and invite you guys once this is merged. They have given me free team plans for open source.

This PR has to be merged first because the `build` script must be available for Netlify to deploy.

**Review by re-fort — APPROVED** [review]

**Comment by re-fort** [comment]
@yyx990803
Okay, I've merged.
Would you also set up custom domain on Netlify?
If so, I'll remove `CNAME`.

**Comment by yyx990803** [comment]
Yes, the CNAME can be removed. I'll deploy a bit later

**Comment by yyx990803** [comment]
Done! The site is now being served by Netlify 🎉

**Comment by re-fort** [comment]
😍🎉

**Comment by kazupon** [comment]
@yyx990803 Thanks!

**Comment by kazupon** [comment]
@yyx990803 Would you like to invitie me and @re-fort  to the `vuejs-jp` team?

**Comment by yyx990803** [comment]
Yeah, you can send me your email address for invite on Slack

**Pull request merged**
